name: Install libcurl on fresh ubuntu runner

on:
   push:

jobs:
  shell:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo apt install -y libcurl4-openssl-dev
